// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/ztx/andra/example/design
// --out=$(GOPATH)/src/github.com/ztx/andra/example
// --version=v1.1.0-dirty
//
// API "entp": Models
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"errors"
	"github.com/ztx/andra/example/app"
	"golang.org/x/net/context"
	"log"
)

// Model for item master
type Item struct {
	ID   *int `gocql:"primary_key"` // primary key
	Code *string
	Name *string
	Uom  *string
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m Item) TableName() string {

	return "item_master"
}

//ValueHolders return a collection of struct field pointers
//specified by the param list
func (m *Item) ValueHolders(attribs ...string) []interface{} {
	var i interface{}
	var val []interface{}
	for _, v := range attribs {
		i = m.ValueHolder(v)
		if i != nil {
			val = append(val, v)
		} else {
			log.Println("Error: No such attribute ", v)
			panic("Error: No such attribute ")
		}
	}
	return val
}

//ValueHolder returns the pointer to struct field identified by name; can be used to
//store the scanned value from db
func (m *Item) ValueHolder(attrib string) interface{} {
	var out interface{}
	switch attrib {

	case "Code":
		out = &m.Code

	case "ID":
		out = &m.ID

	case "Name":
		out = &m.Name

	case "Uom":
		out = &m.Uom

	}
	return out
}

//Validate will validate a model
func (m *Item) Validate() bool {
	if m.ID == nil {
		log.Println(errors.New("Some null fields are found which should not be null"))
		return false
	}

	return true
}

//validates by comparing 2 models
func (im ItemModel) Validate(m1, m2 Item) bool {

	return m1.ID == m2.ID &&
		m1.Validate() && m2.Validate()

}

//Returns true for read only attributes
func (item Item) ReadOnly(attrib string) bool {
	switch attrib {
	case "ID":
		return true
	}
	return false
}

// ItemModel is the implementation of the storage interface for
// Item.
type ItemModel struct {
}

// NewItemModel creates a new storage type.
func NewItemModel() *ItemModel {

	return &ItemModel{}
}

// ItemStorage represents the storage interface.
type ItemStorage interface {
	List(ctx context.Context) ([]*Item, error)
	Get(ctx context.Context, id *int) (*Item, error)
	Add(ctx context.Context, item *Item) error
	Update(ctx context.Context, item *Item) error
	Delete(ctx context.Context, id *int) error

	ListItem(ctx context.Context) []*app.Item
	OneItem(ctx context.Context, id *int) (*app.Item, error)

	UpdateFromCreateItemPayload(ctx context.Context, payload *app.CreateItemPayload, id *int) error
}
