// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/ztx/andra/example/design
// --out=$(GOPATH)/src/github.com/ztx/andra/example
// --version=v1.1.0-dirty
//
// API "entp": Models
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

//Creating LOVs
type ItemType string

const (
	FinishedItem ItemType = "finishedItem"
	MakeItem     ItemType = "makeItem"
)
