// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/ztx/andra/example/design
// --out=$(GOPATH)/src/github.com/ztx/andra/example
// --version=v1.1.0-dirty
//
// API "entp": Models
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"errors"
	"github.com/ztx/andra/example/app"
	"golang.org/x/net/context"
	"log"
	"time"
)

// Model for PR header
type Pr struct {
	ID          *int `gocql:"primary_key"` // primary key
	ApprovedQty *int
	PrDate      *time.Time
	PrNum       *string `sql:"unique_index"`
}

// TableName overrides the table name settings  to force a specific table name
// in the database.
func (m Pr) TableName() string {

	return "pr_header"
}

func (m Pr) PrimaryKeys() []string {
	return []string{"ID"}
}

//ValueHolders return a collection of struct field pointers
//specified by the param list
func (m *Pr) ValueHolders(attribs ...string) []interface{} {
	var i interface{}
	var val []interface{}
	for _, v := range attribs {
		i = m.ValueHolder(v)
		if i != nil {
			val = append(val, v)
		} else {
			log.Println("Error: No such attribute ", v)
			panic("Error: No such attribute ")
		}
	}
	return val
}

//ValueHolder returns the pointer to struct field identified by name; can be used to
//store the scanned value from db
func (m *Pr) ValueHolder(attrib string) interface{} {
	var out interface{}
	switch attrib {

	case "ApprovedQty":
		out = &m.ApprovedQty

	case "ID":
		out = &m.ID

	case "PrDate":
		out = &m.PrDate

	case "PrNum":
		out = &m.PrNum

	}
	return out
}

//if a filed pointer is nil that field will not be returned instead
//a nil is returned
func (m *Pr) ValueHolderNil(attrib string) interface{} {
	var out interface{}
	switch attrib {
	case "ApprovedQty":
		if m.ApprovedQty != nil {
			out = &m.ApprovedQty
		} else {
			out = nil
		}
	case "ID":
		if m.ID != nil {
			out = &m.ID
		} else {
			out = nil
		}
	case "PrDate":
		if m.PrDate != nil {
			out = &m.PrDate
		} else {
			out = nil
		}
	case "PrNum":
		if m.PrNum != nil {
			out = &m.PrNum
		} else {
			out = nil
		}
	}
	return out
}

//Validate will validate a model
func (m *Pr) Validate() bool {
	if m.ID == nil {
		log.Println(errors.New("Some null fields are found which should not be null"))
		return false
	}

	return true
}

//validates by comparing 2 models
func (im PrModel) Validate(m1, m2 Pr) bool {

	return m1.ID == m2.ID &&
		m1.Validate() && m2.Validate()

}

//Returns true for read only attributes
func (item Pr) ReadOnly(attrib string) bool {
	switch attrib {
	case "ID":
		return true
	}
	return false
}

// PrModel is the implementation of the storage interface for
// Pr.
type PrModel struct {
}

// NewPrModel creates a new storage type.
func NewPrModel() *PrModel {

	return &PrModel{}
}

// PrStorage represents the storage interface.
type PrStorage interface {
	List(ctx context.Context) ([]*Pr, error)
	Get(ctx context.Context, id *int) (*Pr, error)
	Add(ctx context.Context, pr *Pr) error
	Update(ctx context.Context, pr *Pr) error
	Delete(ctx context.Context, id *int) error

	ListPrheader(ctx context.Context) []*app.Prheader
	OnePrheader(ctx context.Context, id *int) (*app.Prheader, error)

	UpdateFromCreatePrPayload(ctx context.Context, payload *app.CreatePrPayload, id *int) error
}
