// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/ztx/andra/example/design
// --out=$(GOPATH)/src/github.com/ztx/andra/example
// --version=v1.1.0-dirty
//
// API "entp": Model Helpers
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"context"
	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"github.com/ztx/andra/example/app"
	"time"
)

// MediaType Retrieval Functions

// ListPrheader returns an array of view: default.
func (m *PrDB) ListPrheader(ctx context.Context) []*app.Prheader {
	defer goa.MeasureSince([]string{"goa", "db", "prheader", "listprheader"}, time.Now())

	var native []*Pr
	var objs []*app.Prheader
	err := m.Db.Scopes().Table(m.TableName()).Find(&native).Error

	if err != nil {
		goa.LogError(ctx, "error listing Pr", "error", err.Error())
		return objs
	}

	for _, t := range native {
		objs = append(objs, t.PrToPrheader())
	}

	return objs
}

// PrToPrheader loads a Pr and builds the default view of media type Prheader.
func (m *Pr) PrToPrheader() *app.Prheader {
	pr := &app.Prheader{}
	tmp1 := &m.PrDate
	pr.PrDate = tmp1.PrDateToPrDate() // %!s(MISSING)
	tmp2 := &m.PrNum
	pr.PrNum = tmp2.PrNumToPrNum() // %!s(MISSING)

	return pr
}

// OnePrheader loads a Pr and builds the default view of media type Prheader.
func (m *PrDB) OnePrheader(ctx context.Context, id *int) (*app.Prheader, error) {
	defer goa.MeasureSince([]string{"goa", "db", "prheader", "oneprheader"}, time.Now())

	var native Pr

	if err != nil && err != gorm.ErrRecordNotFound {
		goa.LogError(ctx, "error getting Pr", "error", err.Error())
		return nil, err
	}

	view := *native.PrToPrheader()
	return &view, err
}
