// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/ztx/entp/designsvc
// --out=$(GOPATH)/src/github.com/ztx/entp
// --version=v1.1.0-dirty
//
// API "entp": Application Resource Href Factories
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import (
	"fmt"
	"strings"
)

// PrLineHref returns the resource href.
func PrLineHref(prNum, prLineNum interface{}) string {
	paramprNum := strings.TrimLeftFunc(fmt.Sprintf("%v", prNum), func(r rune) bool { return r == '/' })
	paramprLineNum := strings.TrimLeftFunc(fmt.Sprintf("%v", prLineNum), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/entp/prs/%v/prlines/%v", paramprNum, paramprLineNum)
}

// ItemHref returns the resource href.
func ItemHref(itemCode interface{}) string {
	paramitemCode := strings.TrimLeftFunc(fmt.Sprintf("%v", itemCode), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/entp/items/%v", paramitemCode)
}

// PrHref returns the resource href.
func PrHref(prNum interface{}) string {
	paramprNum := strings.TrimLeftFunc(fmt.Sprintf("%v", prNum), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/entp/prs/%v", paramprNum)
}
