// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/ztx/entp/designsvc
// --out=$(GOPATH)/src/github.com/ztx/entp
// --version=v1.1.0-dirty
//
// API "entp": Application Media Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import "time"

// item details (default view)
//
// Identifier: application/vnd.item+json; view=default
type Item struct {
	// Item Code
	Code *string `form:"code,omitempty" json:"code,omitempty" xml:"code,omitempty"`
	// ID of the item
	ID *int `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// Name of the item
	Name *string `form:"name,omitempty" json:"name,omitempty" xml:"name,omitempty"`
	// Unit Of Measure
	Uom *string `form:"uom,omitempty" json:"uom,omitempty" xml:"uom,omitempty"`
}

// ItemCollection is the media type for an array of Item (default view)
//
// Identifier: application/vnd.item+json; type=collection; view=default
type ItemCollection []*Item

// PR details (default view)
//
// Identifier: application/vnd.prdetails+json; view=default
type Prdetails struct {
	// ID of the item
	ID *int `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// Item
	Item *Item `form:"item,omitempty" json:"item,omitempty" xml:"item,omitempty"`
	// price
	Price *int `form:"price,omitempty" json:"price,omitempty" xml:"price,omitempty"`
	// Quantity
	Qty *int `form:"qty,omitempty" json:"qty,omitempty" xml:"qty,omitempty"`
	// serial number
	Sl *int `form:"sl,omitempty" json:"sl,omitempty" xml:"sl,omitempty"`
}

// PrdetailsCollection is the media type for an array of Prdetails (default view)
//
// Identifier: application/vnd.prdetails+json; type=collection; view=default
type PrdetailsCollection []*Prdetails

// PR header details (default view)
//
// Identifier: application/vnd.prheader+json; view=default
type Prheader struct {
	// pr date
	PrDate *time.Time `form:"prDate,omitempty" json:"prDate,omitempty" xml:"prDate,omitempty"`
	// pr number
	PrNum *string `form:"prNum,omitempty" json:"prNum,omitempty" xml:"prNum,omitempty"`
}

// PrheaderCollection is the media type for an array of Prheader (default view)
//
// Identifier: application/vnd.prheader+json; type=collection; view=default
type PrheaderCollection []*Prheader
